### ISSUE TITLE
Document what changes are needed to achieve solution for DFP

### ISSUE THREAD

**Issue by jefftulsa** [seesawlabs/cortex-html5-base#14]
We need to write up what changes would be necessary to achieve Kiran's second bullet point in his email:

_Locally hosted top-page within which there is an iframe that loads a real domain (amazonaws.com) – Unfortunately, our spam engineers still believe this is going to be an issue in the long run. The campaign may temporarily work in the short run if it is new, but we think it will eventually spam out. I know this is kind of annoying, but is an integration where the *entire* page requested is on a publicly accessible domain feasible?_

**Comment by cjsauer** [comment]
>...is an integration where the entire page requested is on a publicly accessible domain feasible?

At the moment, Cortex devices load up web pages from _local files_. The Chromium browser is pointed to a domain of shape `file:///some/path/to/the/creative`. In order to achieve what Kiran is asking, we'd need to modify the Cortex devices so that they behaved more like a real web browser. Instead of pointing them to a local file, we could point them to, say, `www.intersection.com`. And have it load creatives that way. 

The issue is that there is already a ton of infrastructure in place for the present workflow. We load bundles up into Vistar, and then place them into rotation from there. This is where my knowledge ends. I'm not sure what Vistar does to distribute those bundles to devices. Vistar either _pushes_ the bundles down to all relevant devices, or the devices _pull_ whenever they sense a new bundle is pending. Either way, from my vantage point, it seems like we'd have to change the way that this "udpate phase" happens. Instead of actually downloading the bundles to the devices, we'd have to make Vistar _host_ those creatives, like a real web server.

So the devices' rotation would be something like:

1. Point Chromium browser at `https://vistarmedia.com/creative1`
2. Point Chromium browser at `https://vistarmedia.com/creative2`
3. Point Chromium browser at `https://vistarmedia.com/creative3`
4. etc...

Our team is not able to do this. We don't have access to the Cortex player source code, nor do we have the knowledge to make an effective change. We'd need to talk with the Cortex engineers.

**Comment by ivanmorales** [comment]
There was a conversation with Hamza a while back, I believe it was still DFP related, where he mentioned that whatever asset is loaded runs in an `iframe`.  So regardless if we would be to tell cortex to load a URL, it would still load in their `iframe`.  I believe the reason he said it worked this way was to be able to push state events to the assets themselves for things like preloading and data seeding.

**Comment by jefftulsa** [comment]
@ivanmorales when you say: 

_"So regardless if we would be to tell cortex to load a URL, it would still load in their iframe"_

What is the relevance here? Does this differ from what Kiran is requesting?

**Comment by ivanmorales** [comment]
@jefftulsa By "So regardless if we would be to tell cortex to load a URL ..." I meant that even if we could do what Calvin is proposing:
> Instead of actually downloading the bundles to the devices, we'd have to make Vistar host those creatives, like a real web server.

The Cortex team still loads that URL in their own iframe, so we'd never be outside of a _parent_ iframe.  We would need to make sure that there are no parent iframes for Kiran's solution to work.  If the Cortex team cannot achieve this, then Kiran's solution would be a nonstarter.
