### ISSUE TITLE
JetBlue Campaign

### ISSUE THREAD

**Issue by jefftulsa** [seesawlabs/cortex-html5-base#38]

**Comment by ivanmorales** [comment]
# JetBlue IFrame Creative
## Summary
The initial ask was to load a creative in the same manner that we loaded LivePoser.  Which was to serve two `iframes` and toggle showing the creative between the two.  The difference with this creative was was provided as a zip bundle and not a URL.  This inherent difference made the development not as straight forward as first thought.  A solution would have been to recreate the banner using this repo (cortex-html5-base) but with a timeline of three days, we needed a better solution.

## Backstory
We needed to find a way to serve up an asset into `iframes` that swap visibility from the **parent asset**.   The bundle itself is a small website, that houses html, css and javascript files.  The html and javascript handle the bulk of the business logic that decides which ad to serve.  The creative receives an `ID` from the querystring which is supposed to be the `VENUE ID` from Silo.

The asset also does something new where it toggles to another ad halfway into the asset's play time.  So after 7.5 seconds the asset toggles from a dynamic ad serve to a default ad.  

This exposed two main issues, how to serve the bundle in an `iframe` and how to manage the creative's state from the **parent asset**.  The second problem became inherently more troublesome as normally you're not supposed to be able to communicate between two windows/frames of different origins.

## Solution
### Getting a URL for the iframe
To solve this issue, we hosted the creative in AWS S3 as a static web site.  This immediately fixed the problem of having to recreate the creative (http://linknyc-jetblue.s3-website-us-east-1.amazonaws.com/?crtx_mode=skip).  This URL was then used in the `iframe` toggle asset we already had

### The ad swap
This issue wasn't as apparent at first.  The way the banner is supposed to work is that 7.5 seconds after the dynamic ad is loaded, it displays a default image.  This wouldn't really be a problem, but our implementation of swapping iframes exposed the issue.  Because the iframes are "preloaded" to give them a chance to load any assets, this 7.5 seconds started while the iframe was hidden.  The result was that everytime the iframe was unhidden, it would only show the default image that loaded 7.5 seconds after the iframe's initial load.

To solve this, we needed a way to tell the banner exactly when the banner is visible and because the iframe host is different than the SBC's, there's no direct way to access the creative.  The solution was using a message queue feature built into browsers.  Enter [PostMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)

*parent asset*
```JavaScript
this.iframe.contentWindow.postMessage({
  call: 'sendVisible',
  value: 'VISIBLE'
}, *)
```

*creative*
```JavaScript
window.addEventListener('message', function(event) {
  if (event.data.value === 'VISIBLE') {
    // Start the timer on the default image
  }
});
```

This code allows the parent asset to send messages to the creative so that it knows when it's visible, not just loaded.  I've known of this capability in browsers, but wasn't sure if the Chromium version would be compatible.  In the end it was.

### Attempts
Before I implemented this solution I tried other known ways to communicate:
1. Change the `hash` of the iframe URL.  In some browsers, the nested iframe can poll the URL and essentially receive a message when the URL changes.
2. Change the `name` of the iframe.  In some browsers, the nested iframe can poll it's `window.name` and essentially receive a message when the `name` changes.
